#!/usr/bin/bash

# This program print Markdown SOURCES_SLIDES (slide-deck, standard document) 
# to different formats (HTML, HTML Single Page, PDF, epub) and
# allows to publish them on a ftp server.
#
# This program uses and requires marp, pandoc and lftp.

#Alias and functions

MD2HTML_SLIDES_DECK=(marp --html --allow-local-files)
MD2PDF=(marp --html --theme theme.css --pdf --allow-local-files)
MD2EPUB=(pandoc --from=markdown --to=epub --css=style.css)
OUTPUT_DIR="public"

# Helping function

function show_help() {
    cat <<EOF
Usage: $0 [options]

Options:
  --html-single       Générer HTML Single Page (standalone)
  --no-html-single    Ne pas générer HTML Single Page
  --html-deck         Générer HTML deck
  --no-html-deck      Ne pas générer HTML deck
  --pdf               Générer PDF
  --no-pdf            Ne pas générer PDF
  --epub              Générer EPUB
  --no-epub           Ne pas générer EPUB
  --slides-only       Seulement HTML deck
  -h, --help          Afficher ce message
EOF
    exit 0
}



function md2htmlsingle(){
	filename="${1%%.*}"
	#Create an empty stylesheet if not found
	if [ -e "style.css" ]; then
		echo "Stylesheet style.css found"
	else
		touch style.css
		echo "Empty stylesheet style.css created"
	fi
	pandoc $1 -f markdown+tex_math_double_backslash -t html5 -s -o ${OUTPUT_DIR}/${filename}.html --toc --toc-depth=2 --lua-filter h2-link.lua --standalone  --strip-comments --mathml --css style.css --self-contained
}

#Load options (FTP credentials, format by defaut)
if [[ -f ".env" ]]; then
    source .env
else
    echo ".env not found"
    exit 1
fi

# Handle user options
while [ $# -gt 0 ]; do
    case "$1" in
        --html-single) do_html_single=true ;;
        --no-html-single) do_html_single=false ;;

        --html-deck) do_html_deck=true ;;
        --no-html-deck) do_html_deck=false ;;

        --pdf) do_pdf=true ;;
        --no-pdf) do_pdf=false ;;

        --epub) do_epub=true ;;
        --no-epub) do_epub=false ;;

        --slides-only)
            do_html_single=false
            do_html_deck=true
            do_pdf=false
            do_epub=false
            ;;

        --ftp)
          do_publish_on_ftp_server=true
          ;;

        --all)
            do_html_single=true
            do_html_deck=true
            do_pdf=true
            do_epub=true
            ;;

        -h|--help) show_help ;;
        *)
            echo "Unknown option : $1" >&2
            exit 1
            ;;
    esac
    shift
done

# Print SOURCES_SLIDES to HTML slide-deck, HTML Single Page, PDF and Epub

echo "[ Printing ]"

# Sync assets in public
echo "Sync assets in ${OUTPUT_DIR} ..."
mkdir -p public/assets
cp -rn assets/* "${OUTPUT_DIR}/assets/"
echo "Sync assets in ${OUTPUT_DIR} ... Done"

for file in "${SOURCES_SLIDES[@]}"; do

 if [[ ! -f "$file" ]]; then
        echo "Warning : file $file does not exist. Skipping file."
        continue
 fi

    # Add class to each slide bg img (idempotent)
    sed -i 's/!\[bg \([^]]*\)\](\([^)]*\))\({\.marp-bg-img}\)\?/![bg \1](\2){.marp-bg-img}/g' "$file"

    base=$(basename "$file" .md)

    echo "Publication of $file..."

    if $do_html_deck; then
      echo "Printing $base to HTML Slides Deck ..."
        "${MD2HTML_SLIDES_DECK[@]}" "$file" \
            -o "${OUTPUT_DIR}/${base}-deck.html" \
            2>/dev/null
    fi

    if $do_pdf; then
      echo "Printing $base to PDF..."
        "${MD2PDF[@]}" "$file" \
            -o "${OUTPUT_DIR}/${base}.pdf" \
            2>/dev/null
    fi

    if $do_html_single; then
        echo "Printing $base to HTML Single Page ..."
        md2htmlsingle "$file" 2>/dev/null
    fi

    if $do_epub; then
        echo "Printing $base to EPUB ..."
        "${MD2EPUB[@]}" "$file" \
            -o "${OUTPUT_DIR}/${base}.epub" \
            2>/dev/null
    fi
done


# Publish on ftp server
if $do_publish_on_ftp_server; then

  echo "[ Publication ]"
  echo "Publication on remote FTP server..."

  # Iterate through SOURCES_SLIDES
  for src in "${SOURCES_SLIDES[@]}"; do

    base="${src%.md}"

    #Build collection of files to publish (based on user choices)
    files_to_publish=()
        [ "$do_publish_html_pdf" = true ] && files_to_publish+=("${OUTPUT_DIR}/${base}.pdf")
        [ "$do_publish_html_single" = true ] && files_to_publish+=("${OUTPUT_DIR}/${base}.html")
        [ "$do_publish_html_deck" = true ] && files_to_publish+=("${OUTPUT_DIR}/${base}-deck.html")
        [ "$do_publish_html_epub" = true ] && files_to_publish+=("${OUTPUT_DIR}/${base}.epub")

    # Iterate through publications
     for file in "${files_to_publish[@]}"; do

        echo "Publication of $file..."

        if [[ ! -f "$file" ]]; then
          echo "Error : file $file does not exist."
          continue
        fi
      
        if lftp -u "$FTP_USER","$FTP_PASS" "$FTP_HOST" <<EOF
cd $REMOTE_DIR
put $file
bye
EOF
        then
        echo "File $file published on $FTP_HOST/$REMOTE_DIR !"
        else
        echo "Error: Failed to upload $file" >&2
        fi
    done
  done
fi




