#!/usr/bin/bash

# This program print Markdown SOURCES_SLIDES (slide-deck, standard document) 
# to different formats (HTML, HTML Single Page, PDF, epub) and
# allows to publish them on a ftp server.
#
# This program uses and requires marp, pandoc and lftp.

# == ALIASES ==

WORKING_DIR=$(pwd)
OUTPUT_DIR="$WORKING_DIR/public"
ENV_FILE="$WORKING_DIR/.env"


# == FUNCTIONS ==

function show_help() {
    cat <<EOF
Usage: $0 [options]

Options:
  --html-single       Générer HTML Single Page (standalone)
  --no-html-single    Ne pas générer HTML Single Page
  --html-deck         Générer HTML deck
  --no-html-deck      Ne pas générer HTML deck
  --pdf               Générer PDF
  --no-pdf            Ne pas générer PDF
  --epub              Générer EPUB
  --no-epub           Ne pas générer EPUB
  --slides-only       Seulement HTML (Deck + Single Page)
  --clean             Supprime tout le contenu publié (pas les sources ;))
  -h, --help          Afficher ce message
EOF
    exit 0
}


# Print slide-deck Markdown document to slide-deck html (for live presentation)
function mdslide2htmldeck() {
    filename=$(basename "$file" .md)
    #Create an empty stylesheet if not found
	  if [ ! -e "$WORKING_DIR/style.css" ]; then
      touch "$WORKING_DIR/style.css"
      echo "Local stylesheet (style.css) created"
    fi
    marp --html --allow-local-files --theme "$WORKING_DIR/theme.css" "$1" \
        -o "${OUTPUT_DIR}/${filename}-deck.html"
}

# Print slide-deck Markdown document to standalone HTML document
function mdslide2htmlsingle(){
	filename=$(basename "$file" .md)
	#Create an empty stylesheet if not found
	if [ ! -e "$WORKING_DIR/style.css" ]; then
    touch "$WORKING_DIR/style.css"
    echo "Local stylesheet (style.css) created"
  fi

	pandoc $1 -f markdown+tex_math_double_backslash -t html5 -s -o ${OUTPUT_DIR}/${filename}.html --toc --toc-depth=2 --lua-filter pp-h2-link.lua --standalone  --strip-comments --mathml --css "$WORKING_DIR"/style.css --self-contained
}

# Print standard Markdown document to PDF
 function md2pdf(){
  filename=$(basename "$file" .md)
	#Create an empty stylesheet if not found
	if [ ! -e "$WORKING_DIR/style.css" ]; then
    touch "$WORKING_DIR/style.css"
    echo "Local stylesheet (style.css) created"
  fi
  pandoc $1 -f markdown+tex_math_double_backslash -t html5 -o ${OUTPUT_DIR}/${filename}.pdf --strip-comments --mathml --css "$WORKING_DIR"/style.css
 }

 # Print standard Markdown document to EPUB
 function md2epub(){
  filename=$(basename "$file" .md)
	#Create an empty stylesheet if not found
	if [ ! -e "$WORKING_DIR/style.css" ]; then
    touch "$WORKING_DIR/style.css"
    echo "Local stylesheet (style.css) created"
  fi

  pandoc "$1" \
  -f markdown+tex_math_double_backslash \
  -t epub \
  -o "${OUTPUT_DIR}/${filename}.epub" \
  --css "$WORKING_DIR"/style.css \
  --mathml
 }

# == BEGINNING OF THE SCRIPT ==

#Load options (FTP credentials, print and publish formats)
if [[ -f "$ENV_FILE" ]]; then
    source "$ENV_FILE"
else
    echo "Error: .env not found in $WORKING_DIR."
    exit 1
fi

# Handle user options
while [ $# -gt 0 ]; do
    case "$1" in
        --html-single) do_print_html_single=true ;;
        --no-html-single) do_print_html_single=false ;;

        --html-deck) do_print_html_deck=true ;;
        --no-html-deck) do_print_html_deck=false ;;

        --pdf) do_print_pdf=true ;;
        --no-pdf) do_do_print_pdf=false ;;

        --epub) do_print_epub=true ;;
        --no-epub) do_print_epub=false ;;

        --slides-only)
            do_print_html_single=true
            do_print_html_deck=true
            do_print_pdf=false
            do_print_epub=false
            ;;

        --ftp)
          do_publish_on_ftp_server=true
          ;;

        --all)
            do_publish_html_single=true
            do_publish_html_deck=true
            do_publish_pdf=true
            do_publish_epub=true
            ;;

        --clean)
            echo "Cleaning $OUTPUT_DIR ..."
            rm -rf "$OUTPUT_DIR"/*
            echo "Cleaning publications done."
            exit 0
            ;;

        -h|--help) show_help ;;
        *)
            echo "Unknown option : $1" >&2
            exit 1
            ;;
    esac
    shift
done

# Print SOURCES_SLIDES to HTML slide-deck, HTML Single Page, PDF and Epub

# Prexif all sources.
for i in "${!SOURCES_SLIDES[@]}"; do
    SOURCES_SLIDES[$i]="$WORKING_DIR/${SOURCES_SLIDES[$i]}"
done

for i in "${!SOURCES_DOCS[@]}"; do
    SOURCES_DOCS[$i]="$WORKING_DIR/${SOURCES_DOCS[$i]}"
done

echo "[ Printing ]"

# Sync assets in public
echo "Sync assets in ${OUTPUT_DIR} ..."
mkdir -p "${WORKING_DIR}/public/assets"
cp -rn assets/* "${OUTPUT_DIR}/assets/"
echo "Sync assets in ${OUTPUT_DIR} ... Done"

for file in "${SOURCES_SLIDES[@]}"; do

    if [[ ! -f "$file" ]]; then
        echo "Warning : file $file does not exist. Skipping file."
        continue
    fi

    # Add class to each slide bg img (idempotent)
    sed -i 's/!\[bg \([^]]*\)\](\([^)]*\))\({\.marp-bg-img}\)\?/![bg \1](\2){.marp-bg-img}/g' "$file"

    base=$(basename "$file" .md)

    echo "Publication of  $file... (slide-deck)"

    if $do_print_html_deck; then
       echo "Printing $base to HTML Slides Deck ..."
       mdslide2htmldeck "$file" 2>/dev/null
    fi

    if $do_print_html_single; then
        echo "Printing $base to HTML Single Page ..."
        mdslide2htmlsingle "$file" 2>/dev/null
    fi

    if $do_print_pdf; then
      echo "Printing $base to PDF..."
      md2pdf "$file" 2>/dev/null
    fi

    if $do_print_epub; then
        echo "Printing $base to EPUB ..."
        md2epub "$file" 2>/dev/null
    fi
done


# Print standard document (SOURCES_DOCS)
for file in "${SOURCES_DOCS[@]}"; do

    if [[ ! -f "$file" ]]; then
        echo "Warning : file $file does not exist. Skipping file."
        continue
    fi

    base=$(basename "$file" .md)

    echo "Publication of $file... (standard doc)"

    if $do_print_html_single; then
        echo "Printing $base to HTML ..."
        md2htmlsingle "$file" 2>/dev/null
    fi

    if $do_print_pdf; then
      echo "Printing $base to PDF ..."
      md2pdf "$file" 2>/dev/null
    fi

    if $do_print_epub; then
        echo "Printing $base to EPUB ..."
        md2epub "$file" 2>/dev/null
    fi
done

echo "[ Printing Done ]"
echo "Generated files (prints) in $OUTPUT_DIR:"
find "$OUTPUT_DIR" \( -path "$OUTPUT_DIR/assets" -prune \) -o \( -type f -printf " - %f\n" \)

# Publish on FTP server
if $do_publish_on_ftp_server; then

  echo "[ Publication ]"
  echo "Publication on remote FTP server..."

  # Iterate through all sources
  for src in "${SOURCES_SLIDES[@]}" "${SOURCES_DOCS[@]}"; do

    base="${src%.md}"

    #Build selection of files to publish (based on user choices)
    files_to_publish=()
        [ "$do_publish_html_deck" = true ] && files_to_publish+=("${OUTPUT_DIR}/${base}-deck.html")
        [ "$do_publish_html_single" = true ] && files_to_publish+=("${OUTPUT_DIR}/${base}.html")
        [ "$do_publish_pdf" = true ] && files_to_publish+=("${OUTPUT_DIR}/${base}.pdf")
        [ "$do_publish_epub" = true ] && files_to_publish+=("${OUTPUT_DIR}/${base}.epub")

    # Iterate through selected prints to publish
     for file in "${files_to_publish[@]}"; do

        echo "Publication of $file..."

        if [[ ! -f "$file" ]]; then
          echo "Error : file $file does not exist."
          continue
        fi
      
        if lftp -u "$FTP_USER","$FTP_PASS" "$FTP_HOST" <<EOF
cd $REMOTE_DIR
put $file
bye
EOF
        then
        echo "File $file published on $FTP_HOST/$REMOTE_DIR !"
        else
        echo "Error: Failed to upload $file" >&2
        fi
    done
  done
fi